=== sinanrassam/Animal-Vet-System/animals.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <xsd:annotation>
      <xsd:documentation xml:lang="en">
         animals.xsd XML Schema for defining a animals
      </xsd:documentation>
   </xsd:annotation>

   <xsd:element name="animals">
      <xsd:complexType>
         <xsd:sequence>
            <xsd:element name="description" type="xsd:string"
               minOccurs="0" maxOccurs="1"/>
            <xsd:element name="animal" type="AnimalType"
               minOccurs="0" maxOccurs="unbounded"/>
         </xsd:sequence>
      </xsd:complexType>
   </xsd:element>

   <xsd:complexType name="AnimalType">
      <xsd:sequence>
        <xsd:element name="picURL" type="xsd:string"
            minOccurs="0" maxOccurs="1"/>
        <xsd:element name="symptoms" type="xsd:string"
            minOccurs="0" maxOccurs="1"/>
	<xsd:element name="treatment" type="xsd:string"
            minOccurs="0" maxOccurs="1"/>
        <xsd:element name="dateSeen" type="xsd:string"
            minOccurs="0" maxOccurs="1"/>
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string" use="required"/>
      <xsd:attribute name="species" type="xsd:string" use="required"/>
      <xsd:attribute name="priority" type="xsd:positiveInteger" use="optional"/>
   </xsd:complexType>
</xsd:schema>

=== sinanrassam/Animal-Vet-System/testSave.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!--document of a list of animals in a vet--><animals xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="animals.xsd"><description>Mon May 13 19:24:16 NZST 2019 Animals</description><animal name="Murray" priority="2" species="cat"><picURL>C:\Users\sinan\OneDrive - AUT University\Year 2, Sem 1\COMP610 - Data Structures and Algorithm\DSA\Assignment2\test.jpg</picURL><symptoms>snotty nose</symptoms><treatment>Maxiclear, deworming</treatment><dateSeen>13-05-2019 19:24:09</dateSeen></animal><animal name="Santas Little Helper" priority="3" species="dog"><picURL>santasLittleHelper.jpg</picURL><dateSeen>05-04-2019 11:15:30</dateSeen></animal><animal name="Tilly" priority="3" species="horse"><picURL>Tilly.jpg</picURL><symptoms>Limp foot</symptoms><treatment>Cast on foot, painkillers</treatment><dateSeen>13-05-2019 19:24:04</dateSeen></animal><animal name="Ciri" priority="3" species="cat"><picURL>ciri.jpg</picURL><symptoms>Sore Paws</symptoms><treatment>Overnight stay, cream on paws</treatment><dateSeen>13-05-2019 19:24:07</dateSeen></animal><animal name="luna" priority="5" species="dog"><picURL>luna.jpg</picURL><symptoms>Checkup</symptoms><treatment>Vacinations given</treatment><dateSeen>05-04-2019 00:00:00</dateSeen></animal></animals>

=== sinanrassam/Animal-Vet-System/AnimalsInVet.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- document of a list of computer books -->
<animals 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="animals.xsd">
    <description>
        Yesterdays Animals
    </description>
    <animal name="Murray" species="cat" priority="2">
        <symptoms>snotty nose</symptoms>
        <treatment>Maxiclear, deworming</treatment>
        <dateSeen>05-04-2019 13:35:00</dateSeen>
    </animal>
    <animal name="Tilly" species="horse" priority="1">
        <picURL>Tilly.jpg</picURL>
        <symptoms>Limp foot</symptoms>
        <treatment>Cast on foot, painkillers</treatment>
        <dateSeen>05-04-2019  14:30:00</dateSeen>
    </animal>
    <animal name="Ciri" species="cat" priority="1">
        <picURL>ciri.jpg</picURL>
        <symptoms>Sore Paws</symptoms>
        <treatment>Overnight stay, cream on paws</treatment>
        <dateSeen>05-04-2019  15:30:00</dateSeen>
    </animal>
    <animal name="luna" species="dog" priority="5">
        <picURL>luna.jpg</picURL>
        <symptoms>Checkup</symptoms>
        <treatment>Vacinations given</treatment>
        <dateSeen>05-04-2019  12:00:00</dateSeen>
    </animal>
    <animal name="Santas Little Helper" species="dog" priority="3">
        <picURL>santasLittleHelper.jpg</picURL>
        <dateSeen>05-04-2019  11:15:30</dateSeen>
    </animal>
</animals>
